### ISSUE TITLE
Automatically generate interface from QDoc XML

### ISSUE THREAD

**Issue by taktoa** [wavewave/fficxx#13]
I've written a Haskell parser for the XML output of the Qt documentation generator (`qdoc`). This should be more than the data that `fficxx` needs to generate bindings (I chose `qdoc` because it means that you can specially handle things like Qt signals and slots if you wanted to).

Here's the source for the parser (pardon the mess; I haven't had a chance to clean it up):
https://github.com/taktoa/qdoc2psn/blob/master/src/QDoc/Parser.hs

If you want to generate the documentation XML and you have a project that looks like:

```
src
├── bar
│   ├── baz.cc
│   ├── baz.hh
│   ├── quux.cc
│   └── quux.hh
└── foo
    ├── blub.cc
    ├── blub.hh
    ├── glug.cc
    └── glug.hh
```

then you will want to:

```
$ mkdir doc
$ cd src
$ qdoc doc.qdocconf
$ cd ..
$ mv doc/.index generated.xml
$ rm -rvf doc
```

where `src/doc.qdocconf` looks like:

```
headers.fileextensions = "*.ch *.h *.h++ *.hh *.hpp *.hxx"
sources.fileextensions = "*.c++ *.cc *.cpp *.cxx *.mm *.qml *.qdoc"
outputdir = ../doc
sourcedirs = ./foo ./bar
headerdirs = ./foo ./bar
generateindex = true
```

Then, to parse `generated.xml`, you will want something like
`T.readFile "./generated.xml" >>= parseXML .> parseQXIndex`

There are probably still some bugs in the parser, but I think it mostly works.

**Comment by wavewave** [comment]
Wow, this is great! Thanks for the work and sharing this with me.

**Comment by taktoa** [comment]
Oh, I forgot to mention that it still needs some way of parsing the actual C++ types (e.g.: if you have a function `int foo(std::string bar);` then the data structure will look something like `("int", "foo", [("std::string", "bar")])`).

**Comment by wavewave** [comment]
understood :-) 
More examples are welcome. Please let me and other people know about the setup! Thanks.

**Comment by taktoa** [comment]
BTW, I think qdoc is going to switch over to a clang-based parser, so hopefully we can get even more semantic information out of this.

**Comment by taktoa** [comment]
So, I think there are two feasible approaches for parsing a C++ type, like `"const std::string&"` into structured data in Haskell.

1. Use `libclang` to tokenize the C++ and then do further parsing with, e.g.: Earley.
2. Defer to the user.

### Approach 1

You can fairly easily tokenize a C++ file using libclang:

```c++
#include <iostream>
#include <clang-c/Index.h>

std::ostream& operator<<(std::ostream& stream, const CXString& str) {
    stream << clang_getCString(str); clang_disposeString(str); return stream;
}

int main() {
    CXIndex index = clang_createIndex(0, 0);
    CXTranslationUnit unit = clang_parseTranslationUnit(
        index, "header.hpp", nullptr, 0, nullptr, 0, CXTranslationUnit_None);
    CXSourceRange range = clang_getCursorExtent(
        clang_getTranslationUnitCursor(unit));

    CXToken* tokens; unsigned int numTokens;
    clang_tokenize(unit, range, &tokens, &numTokens);

    for(int i = 0; i < numTokens; i++) {
        const CXToken& tok = tokens[i];
        std::cout << "Token: " << clang_getTokenSpelling(unit, tok) << "\n";
    }

    clang_disposeTokens(unit, tokens, numTokens);
    clang_disposeTranslationUnit(unit);
    clang_disposeIndex(index);
}
```

Then, we would write a Haskell API around this via the FFI (or we could use [LibClang](https://github.com/chetant/LibClang), but I've never been able to get it to compile). Since [Earley](https://hackage.haskell.org/package/Earley) supports writing BNF grammars over arbitrary alphabets, we could then write a parser in terms of the list of tokens.

I think this approach is much easier than either using the Clang AST directly (since it's probably huge and there is no existing Haskell type corresponding to it) or writing a full parser and tokenizer from scratch in Haskell (since I believe Clang has to do some nontrivial analysis to tokenize C++, though I may be wrong).

### Approach 2

We could simply ask the user for a `Map Text CPPTypes` or similar, and perhaps even prompt the user at runtime for anything that's not in the `Map`.

**Comment by wavewave** [comment]
We are not pursuing for QDoc approach. so I close this issue.
