### ISSUE TITLE
The cabal package doesn't compile

### ISSUE THREAD

**Issue by algorev** [wavewave/fficxx#14]
The cabal package doesn't compile. I can't tell on which platforms except macOs Sierra, and the platform in the cabal build log.
the log on macOs Sierra:

$ cabal install fficxx
Resolving dependencies...
Configuring fficxx-0.3.1...
Building fficxx-0.3.1...
Failed to install fficxx-0.3.1
Build log ( /Users/Famille_Pintado/.cabal/logs/fficxx-0.3.1.log ):
cabal: Entering directory '/var/folders/mj/04z51kks2_gbf6294wh02zcc0000gp/T/cabal-tmp-1886/fficxx-0.3.1'
Configuring fficxx-0.3.1...
Building fficxx-0.3.1...
Preprocessing library fficxx-0.3.1...
[ 1 of 16] Compiling FFICXX.Generate.Util.HaskellSrcExts ( lib/FFICXX/Generate/Util/HaskellSrcExts.hs, dist/build/FFICXX/Generate/Util/HaskellSrcExts.o )

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:19:22: error:
    • Expecting one more argument to ‘QName’
      Expected a type, but ‘QName’ has kind ‘* -> *’
    • In the type signature:
        unqual :: String -> QName

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:22:20: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        tycon :: String -> Type

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:25:23: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        conDecl :: String -> [Type] -> ConDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:25:32: error:
    • Expecting one more argument to ‘ConDecl’
      Expected a type, but ‘ConDecl’ has kind ‘* -> *’
    • In the type signature:
        conDecl :: String -> [Type] -> ConDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:28:25: error:
    • Expecting one more argument to ‘Name’
      Expected a type, but ‘Name’ has kind ‘* -> *’
    • In the type signature:
        recDecl :: String -> [([Name], Type)] -> ConDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:28:31: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        recDecl :: String -> [([Name], Type)] -> ConDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:28:41: error:
    • Expecting one more argument to ‘ConDecl’
      Expected a type, but ‘ConDecl’ has kind ‘* -> *’
    • In the type signature:
        recDecl :: String -> [([Name], Type)] -> ConDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:31:28: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        FFICXX.Generate.Util.HaskellSrcExts.app :: String -> String -> Exp

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:34:20: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        mkVar :: String -> Exp

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:37:18: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        con :: String -> Exp

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:40:21: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        mkTVar :: String -> Type

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:43:21: error:
    • Expecting one more argument to ‘Pat’
      Expected a type, but ‘Pat’ has kind ‘* -> *’
    • In the type signature:
        mkPVar :: String -> Pat

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:46:24: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        mkPVarSig :: String -> Type -> Pat

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:46:32: error:
    • Expecting one more argument to ‘Pat’
      Expected a type, but ‘Pat’ has kind ‘* -> *’
    • In the type signature:
        mkPVarSig :: String -> Type -> Pat

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:49:10: error:
    • Expecting one more argument to ‘Pat’
      Expected a type, but ‘Pat’ has kind ‘* -> *’
    • In the type signature:
        pbind :: Pat -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:49:17: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        pbind :: Pat -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:49:30: error:
    • Expecting one more argument to ‘Binds’
      Expected a type, but ‘Binds’ has kind ‘* -> *’
    • In the first argument of ‘Maybe’, namely ‘Binds’
      In the type signature:
        pbind :: Pat -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:49:39: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        pbind :: Pat -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:52:22: error:
    • Expecting one more argument to ‘TyVarBind’
      Expected a type, but ‘TyVarBind’ has kind ‘* -> *’
    • In the type signature:
        mkTBind :: String -> TyVarBind

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:55:23: error:
    • Expecting one more argument to ‘Pat’
      Expected a type, but ‘Pat’ has kind ‘* -> *’
    • In the type signature:
        mkBind1 :: String -> [Pat] -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:55:31: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        mkBind1 :: String -> [Pat] -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:55:44: error:
    • Expecting one more argument to ‘Binds’
      Expected a type, but ‘Binds’ has kind ‘* -> *’
    • In the first argument of ‘Maybe’, namely ‘Binds’
      In the type signature:
        mkBind1 :: String -> [Pat] -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:55:53: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkBind1 :: String -> [Pat] -> Exp -> Maybe Binds -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:59:20: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        mkFun :: String -> Type -> [Pat] -> Exp -> Maybe Binds -> [Decl]

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:59:29: error:
    • Expecting one more argument to ‘Pat’
      Expected a type, but ‘Pat’ has kind ‘* -> *’
    • In the type signature:
        mkFun :: String -> Type -> [Pat] -> Exp -> Maybe Binds -> [Decl]

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:59:37: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        mkFun :: String -> Type -> [Pat] -> Exp -> Maybe Binds -> [Decl]

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:59:50: error:
    • Expecting one more argument to ‘Binds’
      Expected a type, but ‘Binds’ has kind ‘* -> *’
    • In the first argument of ‘Maybe’, namely ‘Binds’
      In the type signature:
        mkFun :: String -> Type -> [Pat] -> Exp -> Maybe Binds -> [Decl]

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:59:60: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkFun :: String -> Type -> [Pat] -> Exp -> Maybe Binds -> [Decl]

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:62:23: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        mkFunSig :: String -> Type -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:62:31: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkFunSig :: String -> Type -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:65:12: error:
    • Expecting one more argument to ‘Context’
      Expected a type, but ‘Context’ has kind ‘* -> *’
    • In the type signature:
        mkClass :: Context -> String -> [TyVarBind] -> [ClassDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:65:34: error:
    • Expecting one more argument to ‘TyVarBind’
      Expected a type, but ‘TyVarBind’ has kind ‘* -> *’
    • In the type signature:
        mkClass :: Context -> String -> [TyVarBind] -> [ClassDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:65:49: error:
    • Expecting one more argument to ‘ClassDecl’
      Expected a type, but ‘ClassDecl’ has kind ‘* -> *’
    • In the type signature:
        mkClass :: Context -> String -> [TyVarBind] -> [ClassDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:65:63: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkClass :: Context -> String -> [TyVarBind] -> [ClassDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:68:15: error:
    • Expecting one more argument to ‘Context’
      Expected a type, but ‘Context’ has kind ‘* -> *’
    • In the type signature:
        mkInstance :: Context -> String -> [Type] -> [InstDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:68:37: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        mkInstance :: Context -> String -> [Type] -> [InstDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:68:47: error:
    • Expecting one more argument to ‘InstDecl’
      Expected a type, but ‘InstDecl’ has kind ‘* -> *’
    • In the type signature:
        mkInstance :: Context -> String -> [Type] -> [InstDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:68:60: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkInstance :: Context -> String -> [Type] -> [InstDecl] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:71:22: error:
    • Expecting one more argument to ‘TyVarBind’
      Expected a type, but ‘TyVarBind’ has kind ‘* -> *’
    • In the type signature:
        mkData :: String
                  -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:71:37: error:
    • Expecting one more argument to ‘QualConDecl’
      Expected a type, but ‘QualConDecl’ has kind ‘* -> *’
    • In the type signature:
        mkData :: String
                  -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:71:54: error:
    • Expecting one more argument to ‘Deriving’
      Expected a type, but ‘Deriving’ has kind ‘* -> *’
    • In the type signature:
        mkData :: String
                  -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:71:67: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkData :: String
                  -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:74:25: error:
    • Expecting one more argument to ‘TyVarBind’
      Expected a type, but ‘TyVarBind’ has kind ‘* -> *’
    • In the type signature:
        mkNewtype :: String
                     -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:74:40: error:
    • Expecting one more argument to ‘QualConDecl’
      Expected a type, but ‘QualConDecl’ has kind ‘* -> *’
    • In the type signature:
        mkNewtype :: String
                     -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:74:57: error:
    • Expecting one more argument to ‘Deriving’
      Expected a type, but ‘Deriving’ has kind ‘* -> *’
    • In the type signature:
        mkNewtype :: String
                     -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:74:70: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkNewtype :: String
                     -> [TyVarBind] -> [QualConDecl] -> [Deriving] -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:77:38: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        mkForImpCcall :: String -> String -> Type -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:77:46: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkForImpCcall :: String -> String -> Type -> Decl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:80:24: error:
    • Expecting one more argument to ‘ModulePragma’
      Expected a type, but ‘ModulePragma’ has kind ‘* -> *’
    • In the type signature:
        mkModule :: String
                    -> [ModulePragma] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:80:42: error:
    • Expecting one more argument to ‘ImportDecl’
      Expected a type, but ‘ImportDecl’ has kind ‘* -> *’
    • In the type signature:
        mkModule :: String
                    -> [ModulePragma] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:80:58: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkModule :: String
                    -> [ModulePragma] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:80:67: error:
    • Expecting one more argument to ‘Module’
      Expected a type, but ‘Module’ has kind ‘* -> *’
    • In the type signature:
        mkModule :: String
                    -> [ModulePragma] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:83:25: error:
    • Expecting one more argument to ‘ModulePragma’
      Expected a type, but ‘ModulePragma’ has kind ‘* -> *’
    • In the type signature:
        mkModuleE :: String
                     -> [ModulePragma]
                        -> [ExportSpec] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:83:43: error:
    • Expecting one more argument to ‘ExportSpec’
      Expected a type, but ‘ExportSpec’ has kind ‘* -> *’
    • In the type signature:
        mkModuleE :: String
                     -> [ModulePragma]
                        -> [ExportSpec] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:83:59: error:
    • Expecting one more argument to ‘ImportDecl’
      Expected a type, but ‘ImportDecl’ has kind ‘* -> *’
    • In the type signature:
        mkModuleE :: String
                     -> [ModulePragma]
                        -> [ExportSpec] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:83:75: error:
    • Expecting one more argument to ‘Decl’
      Expected a type, but ‘Decl’ has kind ‘* -> *’
    • In the type signature:
        mkModuleE :: String
                     -> [ModulePragma]
                        -> [ExportSpec] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:83:84: error:
    • Expecting one more argument to ‘Module’
      Expected a type, but ‘Module’ has kind ‘* -> *’
    • In the type signature:
        mkModuleE :: String
                     -> [ModulePragma]
                        -> [ExportSpec] -> [ImportDecl] -> [Decl] -> Module

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:86:23: error:
    • Expecting one more argument to ‘ImportDecl’
      Expected a type, but ‘ImportDecl’ has kind ‘* -> *’
    • In the type signature:
        mkImport :: String -> ImportDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:89:38: error:
    • Expecting one more argument to ‘ImportDecl’
      Expected a type, but ‘ImportDecl’ has kind ‘* -> *’
    • In the type signature:
        mkImportExp :: String -> [String] -> ImportDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:93:26: error:
    • Expecting one more argument to ‘ImportDecl’
      Expected a type, but ‘ImportDecl’ has kind ‘* -> *’
    • In the type signature:
        mkImportSrc :: String -> ImportDecl

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:96:21: error:
    • Expecting one more argument to ‘ModulePragma’
      Expected a type, but ‘ModulePragma’ has kind ‘* -> *’
    • In the type signature:
        lang :: [String] -> ModulePragma

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:99:8: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        dot :: Exp -> Exp -> Exp

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:99:15: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        dot :: Exp -> Exp -> Exp

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:99:22: error:
    • Expecting one more argument to ‘Exp’
      Expected a type, but ‘Exp’ has kind ‘* -> *’
    • In the type signature:
        dot :: Exp -> Exp -> Exp

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:102:10: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        tyPtr :: Type

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:105:17: error:
    • Expecting one more argument to ‘Type’
      Expected a type, but ‘Type’ has kind ‘* -> *’
    • In the type signature:
        tyForeignPtr :: Type
cabal: Leaving directory '/var/folders/mj/04z51kks2_gbf6294wh02zcc0000gp/T/cabal-tmp-1886/fficxx-0.3.1'
cabal: Error: some packages failed to install:
fficxx-0.3.1 failed during the building phase. The exception was:
ExitFailure 1
$

**Comment by SebastianKG** [comment]
I get the same error on Windows 10 & ghc 7.10.3

**Comment by wavewave** [comment]
This  is due to the API change of haskell-src-exts. The HEAD version now has a constraint: haskell-src-exts >= 1.18. I will upload fficxx on hackage with the new version.

**Comment by algorev** [comment]
Please also document the translated bindings.


-----Original Message-----

**Comment by filterfish** [comment]
Not sure if this is relevant (I'm a newb!) but I'm getting the same error and I've got haskell-src-exts 1.19.1 installed.

**Comment by happysf128** [comment]
I got the same issue with ubuntu 16.04 and Haskell platform 7.10.3.

**Comment by cfhammill** [comment]
I was running into the same problem, trying to build from HEAD now gives me:

```
Resolving dependencies...
Configuring fficxx-0.3.999...
Building fficxx-0.3.999...
Failed to install fficxx-0.3.999
Build log ( /home/chammill/.cabal/logs/fficxx-0.3.999.log ):
cabal: Entering directory '.'
Configuring fficxx-0.3.999...
Building fficxx-0.3.999...
Preprocessing library fficxx-0.3.999...
[ 1 of 16] Compiling FFICXX.Generate.Util.HaskellSrcExts ( lib/FFICXX/Generate/Util/HaskellSrcExts.hs, dist/build/FFICXX/Generate/Util/HaskellSrcExts.o )

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:109:84: error:
    • Couldn't match expected type ‘[Deriving ()]’
                  with actual type ‘Maybe (Deriving ())’
    • In the sixth argument of ‘DataDecl’, namely ‘mderiv’
      In the expression:
        DataDecl () (DataType ()) Nothing declhead qdecls mderiv
      In an equation for ‘mkData’:
          mkData n tbinds qdecls mderiv
            = DataDecl () (DataType ()) Nothing declhead qdecls mderiv
            where
                declhead = mkDeclHead n tbinds

lib/FFICXX/Generate/Util/HaskellSrcExts.hs:113:86: error:
    • Couldn't match expected type ‘[Deriving ()]’
                  with actual type ‘Maybe (Deriving ())’
    • In the sixth argument of ‘DataDecl’, namely ‘mderiv’
      In the expression:
        DataDecl () (NewType ()) Nothing declhead qdecls mderiv
      In an equation for ‘mkNewtype’:
          mkNewtype n tbinds qdecls mderiv
            = DataDecl () (NewType ()) Nothing declhead qdecls mderiv
            where
                declhead = mkDeclHead n tbinds
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
```

**Comment by wavewave** [comment]
yes, i've checked that it is built well. Thanks!
