### ISSUE TITLE
Drop unused `either` dependency

### ISSUE THREAD

**Issue by danichts** [wavewave/fficxx#183]
The [`either`]( https://github.com/wavewave/fficxx/blob/master/fficxx/fficxx.cabal#L27) dep. was added a long time ago but at this moment I haven't found any usage of that
This package is compilable to me with `either` being [_removed_](https://github.com/danichts/gentoo-haskell/commit/dd7df9e6e22c4d4f7ab367c610489104f541449e#diff-675901043d10a311d7f60ebbbbdcacfab87f863d5b0e188bc5c4687f4e8d7402)
Please check out if the dependency can be dropped

**Comment by wavewave** [comment]
Yes. indeed! Thanks a lot for informing this to me!

**Comment by wavewave** [comment]
merged!
