### ISSUE TITLE
unknown symbol

### ISSUE THREAD

**Issue by rodrigob** [wavewave/fficxx#3]
Hello !
I am a Haskell newcomer.

I was looking for the hasHell equivalent of Boost.Python and Rice (for Ruby).
http://www.boost.org/doc/libs/1_54_0/libs/python/doc/tutorial/doc/html/index.html
http://rice.rubyforge.org

fficxx seems to be the closest (although not quite, since Boost.Python and Rice are extensions on C++ to create modules in language X, while fficxx works from the haskell side of things).

I first should mention that
https://github.com/wavewave/fficxx/blob/master/sample/mysample-generator/MySampleGen.hs

did not work out of the box (at all) which multiple differences in the API from 
fficxx-0.1.0.
Was there another MySampleGen.hs that I should have been consulting ?

My "fixed" version is
https://gist.github.com/rodrigob/d406e6d6d642b3fe48a6
(plus some obvious name changes to fit my test case)

After these changes I got things compiling and running. However when I try the created module  (named InpaintingFfi) I get the following error

```
$ cabal-dev ghci
GHCi, version 7.4.2: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package fficxx-runtime-0.1 ... linking ... done.
Ok, modules loaded: InpaintingFfi, InpaintingFfi.InpaintingHaskellInterface, InpaintingFfi.InpaintingHaskellInterface.RawType, InpaintingFfi.InpaintingHaskellInterface.FFI, InpaintingFfi.InpaintingHaskellInterface.Interface, InpaintingFfi.InpaintingHaskellInterface.Cast, InpaintingFfi.InpaintingHaskellInterface.Implementation.
Prelude InpaintingFfi> newInpaintingHaskellInterface 
<interactive>: dist/build/InpaintingFfi/InpaintingHaskellInterface/FFI.o: unknown symbol `InpaintingHaskellInterface_newInpaintingHaskellInterface'
```

any idea of what is going on ?

**Comment by wavewave** [comment]
I think this issue is not valid any more. let me close this.
