### ISSUE TITLE
Explain OOP Modeling?

### ISSUE THREAD

**Issue by Fresheyeball** [wavewave/fficxx#5]
![Please](http://memecrunch.com/meme/5ELN0/begging-please/image.jpg?w=400&c=1)

**Comment by gitfoxi** [comment]
+1

**Comment by wavewave** [comment]
Sorry and thanks for your request! I am now trying to revitalize this project after some quiet period (I am now in Zurihac with this project). My current priority is to provide a better documentation and better examples. I hope that this will result in understandable underlying OOP model description. Thanks for your interests!

**Comment by xavier83** [comment]
Anything yet?

**Comment by wavewave** [comment]
doing it anyway is better than never. :-P
I added some lines to README.md. Thanks for waiting!
